import type { Metadata } from "next";

import { Toaster } from "@/components/ui/sonner";
import { TaskProvider } from "@/contexts/TaskContexts";
import { cn } from "@/lib/utils";
import { Inter, Montserrat, Poppins, Roboto } from "next/font/google";
import "./globals.css";

const robotoHeading = Roboto({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className={cn(
        "h-full",
        "antialiased",
        montserrat.variable,
        poppins.variable,
        "font-sans",
        inter.variable,
        robotoHeading.variable,
      )}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <TaskProvider>
          <Toaster position="top-right" richColors />
          {children}
        </TaskProvider>
      </body>
    </html>
  );
}
